services:
  postgres:
    image: postgres:16
    container_name: smartserve-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartserve
    ports:
      - "5432:5432"
    volumes:
      - smartserve_pg_data:/var/lib/postgresql/data

volumes:
  smartserve_pg_data:
