"""
Data file for Category 6: Smart Home & Security.
Generated programmatically.
"""

SMART_HOME_SERVICES = [
    {
        "id": "a67d4f70-245d-5813-9d48-9fd288e1dbce",
        "name": "CCTV/Camera Installation Service Variation 1",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 1200,
        "duration_minutes": 75,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 1 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 1 services for your home.', 'keywords': ['cctv/camera installation service variation 1', 'smart home', 'installation']},
    },
    {
        "id": "66075a60-6209-592c-8f05-88c118937c5d",
        "name": "CCTV/Camera Installation Service Variation 2",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 1400,
        "duration_minutes": 90,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 2 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 2 services for your home.', 'keywords': ['cctv/camera installation service variation 2', 'smart home', 'installation']},
    },
    {
        "id": "4e3e71a2-a412-5605-af49-fc63375f93b6",
        "name": "CCTV/Camera Installation Service Variation 3",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 1600,
        "duration_minutes": 105,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 3 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 3 services for your home.', 'keywords': ['cctv/camera installation service variation 3', 'smart home', 'installation']},
    },
    {
        "id": "4ff11f6d-96bf-5327-a8e4-dd961adcd046",
        "name": "CCTV/Camera Installation Service Variation 4",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 1800,
        "duration_minutes": 120,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 4 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 4 services for your home.', 'keywords': ['cctv/camera installation service variation 4', 'smart home', 'installation']},
    },
    {
        "id": "6fea0268-604f-519a-ad5c-abdfd1a729fd",
        "name": "CCTV/Camera Installation Service Variation 5",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 2000,
        "duration_minutes": 135,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 5 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 5 services for your home.', 'keywords': ['cctv/camera installation service variation 5', 'smart home', 'installation']},
    },
    {
        "id": "8b8c479d-6a45-5786-b4ab-25221ac13a69",
        "name": "CCTV/Camera Installation Service Variation 6",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 2200,
        "duration_minutes": 150,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 6 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 6 services for your home.', 'keywords': ['cctv/camera installation service variation 6', 'smart home', 'installation']},
    },
    {
        "id": "ca6d27c1-08c7-5464-9667-5a710ee21ca3",
        "name": "CCTV/Camera Installation Service Variation 7",
        "category": "6. Smart Home & Security",
        "subcategory": "CCTV/Camera Installation",
        "price": 2400,
        "duration_minutes": 165,
        "description": "Professional cctv/camera installation service for your smart home.",
        "highlights": ['Expert CCTV/Camera Installation setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional CCTV/Camera Installation Service Variation 7 Services', 'description': 'Book expert CCTV/Camera Installation Service Variation 7 services for your home.', 'keywords': ['cctv/camera installation service variation 7', 'smart home', 'installation']},
    },
    {
        "id": "498d667b-30bc-57fa-b3d2-7d7b1d46408f",
        "name": "Video Doorbells Service Variation 1",
        "category": "6. Smart Home & Security",
        "subcategory": "Video Doorbells",
        "price": 1200,
        "duration_minutes": 75,
        "description": "Professional video doorbells service for your smart home.",
        "highlights": ['Expert Video Doorbells setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Video Doorbells Service Variation 1 Services', 'description': 'Book expert Video Doorbells Service Variation 1 services for your home.', 'keywords': ['video doorbells service variation 1', 'smart home', 'installation']},
    },
    {
        "id": "f7b119f9-13b1-59f1-98e7-62a8a8d9273f",
        "name": "Video Doorbells Service Variation 2",
        "category": "6. Smart Home & Security",
        "subcategory": "Video Doorbells",
        "price": 1400,
        "duration_minutes": 90,
        "description": "Professional video doorbells service for your smart home.",
        "highlights": ['Expert Video Doorbells setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Video Doorbells Service Variation 2 Services', 'description': 'Book expert Video Doorbells Service Variation 2 services for your home.', 'keywords': ['video doorbells service variation 2', 'smart home', 'installation']},
    },
    {
        "id": "37cfa6a0-7a1d-52f2-9505-8c13fb818728",
        "name": "Video Doorbells Service Variation 3",
        "category": "6. Smart Home & Security",
        "subcategory": "Video Doorbells",
        "price": 1600,
        "duration_minutes": 105,
        "description": "Professional video doorbells service for your smart home.",
        "highlights": ['Expert Video Doorbells setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Video Doorbells Service Variation 3 Services', 'description': 'Book expert Video Doorbells Service Variation 3 services for your home.', 'keywords': ['video doorbells service variation 3', 'smart home', 'installation']},
    },
    {
        "id": "b24100aa-9570-547f-98cd-5d68c66dbddb",
        "name": "Video Doorbells Service Variation 4",
        "category": "6. Smart Home & Security",
        "subcategory": "Video Doorbells",
        "price": 1800,
        "duration_minutes": 120,
        "description": "Professional video doorbells service for your smart home.",
        "highlights": ['Expert Video Doorbells setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Video Doorbells Service Variation 4 Services', 'description': 'Book expert Video Doorbells Service Variation 4 services for your home.', 'keywords': ['video doorbells service variation 4', 'smart home', 'installation']},
    },
    {
        "id": "8e6d6f16-3511-5e08-bc92-35f12025e142",
        "name": "Video Doorbells Service Variation 5",
        "category": "6. Smart Home & Security",
        "subcategory": "Video Doorbells",
        "price": 2000,
        "duration_minutes": 135,
        "description": "Professional video doorbells service for your smart home.",
        "highlights": ['Expert Video Doorbells setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Video Doorbells Service Variation 5 Services', 'description': 'Book expert Video Doorbells Service Variation 5 services for your home.', 'keywords': ['video doorbells service variation 5', 'smart home', 'installation']},
    },
    {
        "id": "95f80990-65e5-50cf-94bd-69c75aaa4e69",
        "name": "Smart Locks & Access Control Service Variation 1",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 1200,
        "duration_minutes": 75,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 1 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 1 services for your home.', 'keywords': ['smart locks & access control service variation 1', 'smart home', 'installation']},
    },
    {
        "id": "37ab940a-b8b6-59f4-a683-d15ae462f3af",
        "name": "Smart Locks & Access Control Service Variation 2",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 1400,
        "duration_minutes": 90,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 2 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 2 services for your home.', 'keywords': ['smart locks & access control service variation 2', 'smart home', 'installation']},
    },
    {
        "id": "65b4eb53-7577-519d-b48a-2bd16e49e717",
        "name": "Smart Locks & Access Control Service Variation 3",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 1600,
        "duration_minutes": 105,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 3 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 3 services for your home.', 'keywords': ['smart locks & access control service variation 3', 'smart home', 'installation']},
    },
    {
        "id": "92cd5608-ff4f-5707-bf92-a1c30a111b06",
        "name": "Smart Locks & Access Control Service Variation 4",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 1800,
        "duration_minutes": 120,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 4 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 4 services for your home.', 'keywords': ['smart locks & access control service variation 4', 'smart home', 'installation']},
    },
    {
        "id": "7570d619-e759-5651-afe6-f797e3dacc05",
        "name": "Smart Locks & Access Control Service Variation 5",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 2000,
        "duration_minutes": 135,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 5 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 5 services for your home.', 'keywords': ['smart locks & access control service variation 5', 'smart home', 'installation']},
    },
    {
        "id": "37a1f344-ab86-5ebf-869c-9e26f805cb1d",
        "name": "Smart Locks & Access Control Service Variation 6",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Locks & Access Control",
        "price": 2200,
        "duration_minutes": 150,
        "description": "Professional smart locks & access control service for your smart home.",
        "highlights": ['Expert Smart Locks & Access Control setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Locks & Access Control Service Variation 6 Services', 'description': 'Book expert Smart Locks & Access Control Service Variation 6 services for your home.', 'keywords': ['smart locks & access control service variation 6', 'smart home', 'installation']},
    },
    {
        "id": "b542de45-1772-55c6-831a-1857e2534465",
        "name": "Alarm & Sensor Systems Service Variation 1",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 1200,
        "duration_minutes": 75,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 1 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 1 services for your home.', 'keywords': ['alarm & sensor systems service variation 1', 'smart home', 'installation']},
    },
    {
        "id": "0e851c0a-84d4-5afb-ae7d-0e0c2437e626",
        "name": "Alarm & Sensor Systems Service Variation 2",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 1400,
        "duration_minutes": 90,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 2 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 2 services for your home.', 'keywords': ['alarm & sensor systems service variation 2', 'smart home', 'installation']},
    },
    {
        "id": "ade4e808-0a25-57d1-aedf-ce4675b91799",
        "name": "Alarm & Sensor Systems Service Variation 3",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 1600,
        "duration_minutes": 105,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 3 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 3 services for your home.', 'keywords': ['alarm & sensor systems service variation 3', 'smart home', 'installation']},
    },
    {
        "id": "5bde4e4d-cdb9-55ec-9ab8-37292638bffa",
        "name": "Alarm & Sensor Systems Service Variation 4",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 1800,
        "duration_minutes": 120,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 4 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 4 services for your home.', 'keywords': ['alarm & sensor systems service variation 4', 'smart home', 'installation']},
    },
    {
        "id": "a69d6500-8c3d-5141-9372-0a7948e42b6e",
        "name": "Alarm & Sensor Systems Service Variation 5",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 2000,
        "duration_minutes": 135,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 5 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 5 services for your home.', 'keywords': ['alarm & sensor systems service variation 5', 'smart home', 'installation']},
    },
    {
        "id": "9568064a-7915-5aa9-ae1a-f94af8e1fc12",
        "name": "Alarm & Sensor Systems Service Variation 6",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 2200,
        "duration_minutes": 150,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 6 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 6 services for your home.', 'keywords': ['alarm & sensor systems service variation 6', 'smart home', 'installation']},
    },
    {
        "id": "d2f0b4d6-9668-51e3-b38a-fee45502db49",
        "name": "Alarm & Sensor Systems Service Variation 7",
        "category": "6. Smart Home & Security",
        "subcategory": "Alarm & Sensor Systems",
        "price": 2400,
        "duration_minutes": 165,
        "description": "Professional alarm & sensor systems service for your smart home.",
        "highlights": ['Expert Alarm & Sensor Systems setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Alarm & Sensor Systems Service Variation 7 Services', 'description': 'Book expert Alarm & Sensor Systems Service Variation 7 services for your home.', 'keywords': ['alarm & sensor systems service variation 7', 'smart home', 'installation']},
    },
    {
        "id": "e2f0890f-da86-515c-bac5-bd65bc73b5d9",
        "name": "Smart Lighting/Switches Service Variation 1",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Lighting/Switches",
        "price": 1200,
        "duration_minutes": 75,
        "description": "Professional smart lighting/switches service for your smart home.",
        "highlights": ['Expert Smart Lighting/Switches setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Lighting/Switches Service Variation 1 Services', 'description': 'Book expert Smart Lighting/Switches Service Variation 1 services for your home.', 'keywords': ['smart lighting/switches service variation 1', 'smart home', 'installation']},
    },
    {
        "id": "78f4f8dd-d22b-5c0f-b200-48bfe3f7d7d3",
        "name": "Smart Lighting/Switches Service Variation 2",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Lighting/Switches",
        "price": 1400,
        "duration_minutes": 90,
        "description": "Professional smart lighting/switches service for your smart home.",
        "highlights": ['Expert Smart Lighting/Switches setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Lighting/Switches Service Variation 2 Services', 'description': 'Book expert Smart Lighting/Switches Service Variation 2 services for your home.', 'keywords': ['smart lighting/switches service variation 2', 'smart home', 'installation']},
    },
    {
        "id": "11e176e7-7858-5027-a21b-254ee0a13f5b",
        "name": "Smart Lighting/Switches Service Variation 3",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Lighting/Switches",
        "price": 1600,
        "duration_minutes": 105,
        "description": "Professional smart lighting/switches service for your smart home.",
        "highlights": ['Expert Smart Lighting/Switches setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Lighting/Switches Service Variation 3 Services', 'description': 'Book expert Smart Lighting/Switches Service Variation 3 services for your home.', 'keywords': ['smart lighting/switches service variation 3', 'smart home', 'installation']},
    },
    {
        "id": "228282a0-e1db-5968-9075-7aadeeffd9d9",
        "name": "Smart Lighting/Switches Service Variation 4",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Lighting/Switches",
        "price": 1800,
        "duration_minutes": 120,
        "description": "Professional smart lighting/switches service for your smart home.",
        "highlights": ['Expert Smart Lighting/Switches setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Lighting/Switches Service Variation 4 Services', 'description': 'Book expert Smart Lighting/Switches Service Variation 4 services for your home.', 'keywords': ['smart lighting/switches service variation 4', 'smart home', 'installation']},
    },
    {
        "id": "44bdaeee-a1bd-57b2-a909-3d3e7f7a977e",
        "name": "Smart Lighting/Switches Service Variation 5",
        "category": "6. Smart Home & Security",
        "subcategory": "Smart Lighting/Switches",
        "price": 2000,
        "duration_minutes": 135,
        "description": "Professional smart lighting/switches service for your smart home.",
        "highlights": ['Expert Smart Lighting/Switches setup', 'Secure configuration', 'Post-installation demo', '24/7 Support available'],
        "included": ['Standard installation', 'Basic setup and testing', 'Clean up post-service', 'System demonstration'],
        "excluded": ['Major structural modifications', 'Cost of equipment (unless specified)'],
        "process_steps": [{'step_number': 1, 'title': 'Inspection', 'description': 'Site inspection for optimal placement'}, {'step_number': 2, 'title': 'Installation', 'description': 'Mounting and wiring of the device'}, {'step_number': 3, 'title': 'Configuration', 'description': 'Connecting the device to the smart network'}, {'step_number': 4, 'title': 'Testing', 'description': 'Functional testing and system verification'}, {'step_number': 5, 'title': 'Handover', 'description': 'Demonstrating usage and safety guidelines to the customer'}],
        "tools_materials": ['Drill machine', 'Screwdrivers', 'Wire strippers', 'Mounting hardware'],
        "customer_setup": ['Ensure Wi-Fi availability', 'Provide access to installation points'],
        "aftercare": ['Do not touch exposed wiring before setup is complete', 'Keep devices clean from dust'],
        "expected_results": "Fully functional smart home system.",
        "important_notes": "Wi-Fi connectivity issues are not covered under installation warranty.",
        "warranty": "30 days service warranty.",
        "faqs": [{'question': 'Do you provide the devices?', 'answer': 'No, this is an installation service only unless specified.'}, {'question': 'How long does the installation take?', 'answer': 'Typically 1 to 2 hours depending on complexity.'}, {'question': 'Do I need to be home during the service?', 'answer': 'Yes, someone needs to be present to grant access and verify the setup.'}, {'question': 'Is the installation covered by warranty?', 'answer': 'Yes, we provide a 30-day service warranty on our work.'}],
        "tips": ['Change default passwords immediately after setup.'],
        "dos": ['Connect devices to a secure network.'],
        "donts": ['Do not expose indoor cameras to outdoor environments.'],
        "service_features": ['Expert Technicians', 'Secure Setup', 'Guaranteed Quality'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Smart Lighting/Switches Service Variation 5 Services', 'description': 'Book expert Smart Lighting/Switches Service Variation 5 services for your home.', 'keywords': ['smart lighting/switches service variation 5', 'smart home', 'installation']},
    },
]
