"""
Data file for Category 9: Health, Fitness & Wellness.
Generated programmatically.
"""

HEALTH_FITNESS_SERVICES = [
    {
        "id": "325a2da2-5d9e-5689-ae7e-1a64c5934358",
        "name": "Yoga & Meditation Service Variation 1",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 1200,
        "duration_minutes": 60,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 1', 'description': 'Experience expert Yoga & Meditation Service Variation 1 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 1', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "b2e904fb-9bf8-577e-b11f-c1497a08ff68",
        "name": "Yoga & Meditation Service Variation 2",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 1400,
        "duration_minutes": 75,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 2', 'description': 'Experience expert Yoga & Meditation Service Variation 2 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 2', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "37423b94-8ad3-5ffe-9bbc-6ffc64053bef",
        "name": "Yoga & Meditation Service Variation 3",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 1600,
        "duration_minutes": 90,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 3', 'description': 'Experience expert Yoga & Meditation Service Variation 3 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 3', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "a19e0396-6423-5eb5-86cc-79610f36e0a8",
        "name": "Yoga & Meditation Service Variation 4",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 1800,
        "duration_minutes": 105,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 4', 'description': 'Experience expert Yoga & Meditation Service Variation 4 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 4', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "f5b2a772-3ace-5c85-a8ad-55437e913f65",
        "name": "Yoga & Meditation Service Variation 5",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 2000,
        "duration_minutes": 120,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 5', 'description': 'Experience expert Yoga & Meditation Service Variation 5 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 5', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "014dbb7c-f2a5-5154-91f1-c72511dfd9bc",
        "name": "Yoga & Meditation Service Variation 6",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Yoga & Meditation",
        "price": 2200,
        "duration_minutes": 135,
        "description": "Expert yoga & meditation focused on enhancing your overall wellness.",
        "highlights": ['Certified Yoga & Meditation Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 6', 'description': 'Experience expert Yoga & Meditation Service Variation 6 services tailored for your well-being.', 'keywords': ['yoga & meditation service variation 6', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "ddc2f5a0-2e6f-5cd5-bba3-2b2359f6d683",
        "name": "Personal Training Service Variation 1",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 1200,
        "duration_minutes": 60,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 1', 'description': 'Experience expert Personal Training Service Variation 1 services tailored for your well-being.', 'keywords': ['personal training service variation 1', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "402ea739-d08c-56b4-9c11-96ec3b865db2",
        "name": "Personal Training Service Variation 2",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 1400,
        "duration_minutes": 75,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 2', 'description': 'Experience expert Personal Training Service Variation 2 services tailored for your well-being.', 'keywords': ['personal training service variation 2', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "fa27681f-33b2-59a3-b0b2-5a25e2e81830",
        "name": "Personal Training Service Variation 3",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 1600,
        "duration_minutes": 90,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 3', 'description': 'Experience expert Personal Training Service Variation 3 services tailored for your well-being.', 'keywords': ['personal training service variation 3', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "6e776f8b-dd09-5612-88ba-c333ebaa6027",
        "name": "Personal Training Service Variation 4",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 1800,
        "duration_minutes": 105,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 4', 'description': 'Experience expert Personal Training Service Variation 4 services tailored for your well-being.', 'keywords': ['personal training service variation 4', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "4f1ccaa5-994d-5bcb-95ce-9923b894b0ce",
        "name": "Personal Training Service Variation 5",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 2000,
        "duration_minutes": 120,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 5', 'description': 'Experience expert Personal Training Service Variation 5 services tailored for your well-being.', 'keywords': ['personal training service variation 5', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "953ecc43-5088-51ab-8b86-d4758c55357f",
        "name": "Personal Training Service Variation 6",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Personal Training",
        "price": 2200,
        "duration_minutes": 135,
        "description": "Expert personal training focused on enhancing your overall wellness.",
        "highlights": ['Certified Personal Training Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 6', 'description': 'Experience expert Personal Training Service Variation 6 services tailored for your well-being.', 'keywords': ['personal training service variation 6', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "0c2ad276-9094-527f-abf9-fe87d066b22f",
        "name": "Diet & Nutrition Service Variation 1",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 1200,
        "duration_minutes": 60,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 1', 'description': 'Experience expert Diet & Nutrition Service Variation 1 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 1', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "9256c5e4-81d3-5733-8bf3-ffe2fb8d546c",
        "name": "Diet & Nutrition Service Variation 2",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 1400,
        "duration_minutes": 75,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 2', 'description': 'Experience expert Diet & Nutrition Service Variation 2 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 2', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "d24162b7-7c26-515c-81d2-a2dd1b6d6b9c",
        "name": "Diet & Nutrition Service Variation 3",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 1600,
        "duration_minutes": 90,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 3', 'description': 'Experience expert Diet & Nutrition Service Variation 3 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 3', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "e12e5534-f1b9-5152-a626-1c2ce39fc8ce",
        "name": "Diet & Nutrition Service Variation 4",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 1800,
        "duration_minutes": 105,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 4', 'description': 'Experience expert Diet & Nutrition Service Variation 4 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 4', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "a1ebe5ec-fd28-597b-a1ba-7d1dfbc3ab88",
        "name": "Diet & Nutrition Service Variation 5",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 2000,
        "duration_minutes": 120,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 5', 'description': 'Experience expert Diet & Nutrition Service Variation 5 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 5', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "73444069-ba40-5669-bdc3-9772343dcc3f",
        "name": "Diet & Nutrition Service Variation 6",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Diet & Nutrition",
        "price": 2200,
        "duration_minutes": 135,
        "description": "Expert diet & nutrition focused on enhancing your overall wellness.",
        "highlights": ['Certified Diet & Nutrition Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Diet & Nutrition Service Variation 6', 'description': 'Experience expert Diet & Nutrition Service Variation 6 services tailored for your well-being.', 'keywords': ['diet & nutrition service variation 6', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "086fef9d-c302-517a-b45d-28dd67d5cb5a",
        "name": "Physiotherapy Service Variation 1",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 1200,
        "duration_minutes": 60,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 1', 'description': 'Experience expert Physiotherapy Service Variation 1 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 1', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "3f36e9ac-b96d-5a4e-9e23-317f0f199f9a",
        "name": "Physiotherapy Service Variation 2",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 1400,
        "duration_minutes": 75,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 2', 'description': 'Experience expert Physiotherapy Service Variation 2 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 2', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "6c5c273c-3ccd-5f47-9cda-f39ae93a9945",
        "name": "Physiotherapy Service Variation 3",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 1600,
        "duration_minutes": 90,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 3', 'description': 'Experience expert Physiotherapy Service Variation 3 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 3', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "399364d1-7439-53fc-b3a6-36c0c73de25d",
        "name": "Physiotherapy Service Variation 4",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 1800,
        "duration_minutes": 105,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 4', 'description': 'Experience expert Physiotherapy Service Variation 4 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 4', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "2566f951-af68-5072-a8cb-65932557d02c",
        "name": "Physiotherapy Service Variation 5",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 2000,
        "duration_minutes": 120,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 5', 'description': 'Experience expert Physiotherapy Service Variation 5 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 5', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "00ccf016-fafe-5c5d-8694-cd4911f64e90",
        "name": "Physiotherapy Service Variation 6",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Physiotherapy",
        "price": 2200,
        "duration_minutes": 135,
        "description": "Expert physiotherapy focused on enhancing your overall wellness.",
        "highlights": ['Certified Physiotherapy Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy Service Variation 6', 'description': 'Experience expert Physiotherapy Service Variation 6 services tailored for your well-being.', 'keywords': ['physiotherapy service variation 6', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "204889e8-705a-5bb2-ade8-da7ce42762ec",
        "name": "Mental Health Counseling Service Variation 1",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 1200,
        "duration_minutes": 60,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 1', 'description': 'Experience expert Mental Health Counseling Service Variation 1 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 1', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "f6667c15-c1ab-551f-a939-407f293cb264",
        "name": "Mental Health Counseling Service Variation 2",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 1400,
        "duration_minutes": 75,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 2', 'description': 'Experience expert Mental Health Counseling Service Variation 2 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 2', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "8779e21f-7909-588c-8d1f-c83a1d0ce9f6",
        "name": "Mental Health Counseling Service Variation 3",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 1600,
        "duration_minutes": 90,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 3', 'description': 'Experience expert Mental Health Counseling Service Variation 3 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 3', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "e802b517-8b47-5d0b-b47a-6768c187a156",
        "name": "Mental Health Counseling Service Variation 4",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 1800,
        "duration_minutes": 105,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 4', 'description': 'Experience expert Mental Health Counseling Service Variation 4 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 4', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "5b7013df-172b-5a09-ab5e-6363466c7fb6",
        "name": "Mental Health Counseling Service Variation 5",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 2000,
        "duration_minutes": 120,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 5', 'description': 'Experience expert Mental Health Counseling Service Variation 5 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 5', 'health', 'fitness', 'wellness', 'training']},
    },
    {
        "id": "2ba5e27c-d7ff-5126-ab96-d424a12c30d2",
        "name": "Mental Health Counseling Service Variation 6",
        "category": "9. Health, Fitness & Wellness",
        "subcategory": "Mental Health Counseling",
        "price": 2200,
        "duration_minutes": 135,
        "description": "Expert mental health counseling focused on enhancing your overall wellness.",
        "highlights": ['Certified Mental Health Counseling Expert', 'Personalized approach', 'Flexible scheduling', 'Comprehensive evaluation'],
        "included": ['Initial consultation', 'Customized wellness plan', 'Professional guidance', 'Progress monitoring'],
        "excluded": ['Cost of dietary supplements', 'Specialized fitness equipment for home use'],
        "process_steps": [{'step_number': 1, 'title': 'Assessment', 'description': 'Evaluating current health and fitness levels'}, {'step_number': 2, 'title': 'Goal Setting', 'description': 'Defining achievable health and wellness objectives'}, {'step_number': 3, 'title': 'Plan Creation', 'description': 'Developing a personalized routine or diet plan'}, {'step_number': 4, 'title': 'Execution', 'description': 'Guided sessions to implement the plan effectively'}, {'step_number': 5, 'title': 'Review', 'description': 'Regular check-ins to track progress and adjust the plan'}],
        "tools_materials": ['Basic fitness props (e.g., yoga mats)', 'Measurement tools', 'Educational resources'],
        "customer_setup": ['Ensure a comfortable and quiet space', 'Wear appropriate clothing for physical activities'],
        "aftercare": ['Stay hydrated', 'Follow post-session recovery guidelines'],
        "expected_results": "Improved physical fitness and mental well-being.",
        "important_notes": "Please disclose any pre-existing medical conditions before starting.",
        "warranty": "Quality service guarantee; satisfaction assured.",
        "faqs": [{'question': 'Do I need any special equipment?', 'answer': 'Basic props may be needed, but we will inform you in advance.'}, {'question': 'How often should I book a session?', 'answer': 'We recommend at least 2-3 sessions a week for optimal results.'}, {'question': 'Can the diet plan be customized for allergies?', 'answer': 'Yes, all our plans are highly personalized to your dietary needs.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our trainers and consultants are certified professionals.'}],
        "tips": ['Consistency is key to achieving wellness goals.'],
        "dos": ['Communicate openly about any discomfort during sessions.', 'Follow the prescribed plan diligently.'],
        "donts": ['Do not push yourself beyond your physical limits.'],
        "service_features": ['Certified Professionals', 'Personalized Plans', 'Holistic Approach'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Health Counseling Service Variation 6', 'description': 'Experience expert Mental Health Counseling Service Variation 6 services tailored for your well-being.', 'keywords': ['mental health counseling service variation 6', 'health', 'fitness', 'wellness', 'training']},
    },
]
