"""
Data file auto-generated.
"""

HEALTH_FITNESS_SERVICES = [
    {
        "id": '325a2da2-5d9e-5689-ae7e-1a64c5934358',
        "name": 'Personal Training Service Variation 1',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 950,
        "duration_minutes": 60,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 1 Services', 'description': 'Book certified personal training service variation 1 for your health and wellness needs.', 'keywords': ['personal training service variation 1', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'b2e904fb-9bf8-577e-b11f-c1497a08ff68',
        "name": 'Personal Training Service Variation 2',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1100,
        "duration_minutes": 75,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 2 Services', 'description': 'Book certified personal training service variation 2 for your health and wellness needs.', 'keywords': ['personal training service variation 2', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '37423b94-8ad3-5ffe-9bbc-6ffc64053bef',
        "name": 'Personal Training Service Variation 3',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1250,
        "duration_minutes": 90,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 3 Services', 'description': 'Book certified personal training service variation 3 for your health and wellness needs.', 'keywords': ['personal training service variation 3', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'a19e0396-6423-5eb5-86cc-79610f36e0a8',
        "name": 'Personal Training Service Variation 4',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1400,
        "duration_minutes": 105,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 4 Services', 'description': 'Book certified personal training service variation 4 for your health and wellness needs.', 'keywords': ['personal training service variation 4', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'f5b2a772-3ace-5c85-a8ad-55437e913f65',
        "name": 'Personal Training Service Variation 5',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1550,
        "duration_minutes": 120,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 5 Services', 'description': 'Book certified personal training service variation 5 for your health and wellness needs.', 'keywords': ['personal training service variation 5', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '014dbb7c-f2a5-5154-91f1-c72511dfd9bc',
        "name": 'Personal Training Service Variation 6',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1700,
        "duration_minutes": 135,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 6 Services', 'description': 'Book certified personal training service variation 6 for your health and wellness needs.', 'keywords': ['personal training service variation 6', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'e7631e11-38b8-5458-bacb-5a6fffcd9bb6',
        "name": 'Personal Training Service Variation 7',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Personal Training',
        "price": 1850,
        "duration_minutes": 150,
        "description": 'Professional personal training service designed for holistic well-being.',
        "highlights": ['Certified Personal Training specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Personal Training Service Variation 7 Services', 'description': 'Book certified personal training service variation 7 for your health and wellness needs.', 'keywords': ['personal training service variation 7', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'ddc2f5a0-2e6f-5cd5-bba3-2b2359f6d683',
        "name": 'Yoga & Meditation Service Variation 1',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 950,
        "duration_minutes": 60,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 1 Services', 'description': 'Book certified yoga & meditation service variation 1 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 1', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '402ea739-d08c-56b4-9c11-96ec3b865db2',
        "name": 'Yoga & Meditation Service Variation 2',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 1100,
        "duration_minutes": 75,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 2 Services', 'description': 'Book certified yoga & meditation service variation 2 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 2', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'fa27681f-33b2-59a3-b0b2-5a25e2e81830',
        "name": 'Yoga & Meditation Service Variation 3',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 1250,
        "duration_minutes": 90,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 3 Services', 'description': 'Book certified yoga & meditation service variation 3 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 3', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '6e776f8b-dd09-5612-88ba-c333ebaa6027',
        "name": 'Yoga & Meditation Service Variation 4',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 1400,
        "duration_minutes": 105,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 4 Services', 'description': 'Book certified yoga & meditation service variation 4 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 4', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '4f1ccaa5-994d-5bcb-95ce-9923b894b0ce',
        "name": 'Yoga & Meditation Service Variation 5',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 1550,
        "duration_minutes": 120,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 5 Services', 'description': 'Book certified yoga & meditation service variation 5 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 5', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '953ecc43-5088-51ab-8b86-d4758c55357f',
        "name": 'Yoga & Meditation Service Variation 6',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Yoga & Meditation',
        "price": 1700,
        "duration_minutes": 135,
        "description": 'Professional yoga & meditation service designed for holistic well-being.',
        "highlights": ['Certified Yoga & Meditation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Yoga & Meditation Service Variation 6 Services', 'description': 'Book certified yoga & meditation service variation 6 for your health and wellness needs.', 'keywords': ['yoga & meditation service variation 6', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '0c2ad276-9094-527f-abf9-fe87d066b22f',
        "name": 'Physiotherapy & Rehabilitation Service Variation 1',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 950,
        "duration_minutes": 60,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 1 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 1 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 1', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '9256c5e4-81d3-5733-8bf3-ffe2fb8d546c',
        "name": 'Physiotherapy & Rehabilitation Service Variation 2',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 1100,
        "duration_minutes": 75,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 2 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 2 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 2', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'd24162b7-7c26-515c-81d2-a2dd1b6d6b9c',
        "name": 'Physiotherapy & Rehabilitation Service Variation 3',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 1250,
        "duration_minutes": 90,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 3 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 3 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 3', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'e12e5534-f1b9-5152-a626-1c2ce39fc8ce',
        "name": 'Physiotherapy & Rehabilitation Service Variation 4',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 1400,
        "duration_minutes": 105,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 4 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 4 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 4', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'a1ebe5ec-fd28-597b-a1ba-7d1dfbc3ab88',
        "name": 'Physiotherapy & Rehabilitation Service Variation 5',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 1550,
        "duration_minutes": 120,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 5 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 5 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 5', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '73444069-ba40-5669-bdc3-9772343dcc3f',
        "name": 'Physiotherapy & Rehabilitation Service Variation 6',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Physiotherapy & Rehabilitation',
        "price": 1700,
        "duration_minutes": 135,
        "description": 'Professional physiotherapy & rehabilitation service designed for holistic well-being.',
        "highlights": ['Certified Physiotherapy & Rehabilitation specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Physiotherapy & Rehabilitation Service Variation 6 Services', 'description': 'Book certified physiotherapy & rehabilitation service variation 6 for your health and wellness needs.', 'keywords': ['physiotherapy & rehabilitation service variation 6', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '086fef9d-c302-517a-b45d-28dd67d5cb5a',
        "name": 'Nutrition & Diet Counselling Service Variation 1',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Nutrition & Diet Counselling',
        "price": 950,
        "duration_minutes": 60,
        "description": 'Professional nutrition & diet counselling service designed for holistic well-being.',
        "highlights": ['Certified Nutrition & Diet Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Nutrition & Diet Counselling Service Variation 1 Services', 'description': 'Book certified nutrition & diet counselling service variation 1 for your health and wellness needs.', 'keywords': ['nutrition & diet counselling service variation 1', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '3f36e9ac-b96d-5a4e-9e23-317f0f199f9a',
        "name": 'Nutrition & Diet Counselling Service Variation 2',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Nutrition & Diet Counselling',
        "price": 1100,
        "duration_minutes": 75,
        "description": 'Professional nutrition & diet counselling service designed for holistic well-being.',
        "highlights": ['Certified Nutrition & Diet Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Nutrition & Diet Counselling Service Variation 2 Services', 'description': 'Book certified nutrition & diet counselling service variation 2 for your health and wellness needs.', 'keywords': ['nutrition & diet counselling service variation 2', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '6c5c273c-3ccd-5f47-9cda-f39ae93a9945',
        "name": 'Nutrition & Diet Counselling Service Variation 3',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Nutrition & Diet Counselling',
        "price": 1250,
        "duration_minutes": 90,
        "description": 'Professional nutrition & diet counselling service designed for holistic well-being.',
        "highlights": ['Certified Nutrition & Diet Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Nutrition & Diet Counselling Service Variation 3 Services', 'description': 'Book certified nutrition & diet counselling service variation 3 for your health and wellness needs.', 'keywords': ['nutrition & diet counselling service variation 3', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '399364d1-7439-53fc-b3a6-36c0c73de25d',
        "name": 'Nutrition & Diet Counselling Service Variation 4',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Nutrition & Diet Counselling',
        "price": 1400,
        "duration_minutes": 105,
        "description": 'Professional nutrition & diet counselling service designed for holistic well-being.',
        "highlights": ['Certified Nutrition & Diet Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Nutrition & Diet Counselling Service Variation 4 Services', 'description': 'Book certified nutrition & diet counselling service variation 4 for your health and wellness needs.', 'keywords': ['nutrition & diet counselling service variation 4', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '2566f951-af68-5072-a8cb-65932557d02c',
        "name": 'Nutrition & Diet Counselling Service Variation 5',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Nutrition & Diet Counselling',
        "price": 1550,
        "duration_minutes": 120,
        "description": 'Professional nutrition & diet counselling service designed for holistic well-being.',
        "highlights": ['Certified Nutrition & Diet Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Nutrition & Diet Counselling Service Variation 5 Services', 'description': 'Book certified nutrition & diet counselling service variation 5 for your health and wellness needs.', 'keywords': ['nutrition & diet counselling service variation 5', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '204889e8-705a-5bb2-ade8-da7ce42762ec',
        "name": 'Mental Wellness & Counselling Service Variation 1',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 950,
        "duration_minutes": 60,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 1 Services', 'description': 'Book certified mental wellness & counselling service variation 1 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 1', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'f6667c15-c1ab-551f-a939-407f293cb264',
        "name": 'Mental Wellness & Counselling Service Variation 2',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 1100,
        "duration_minutes": 75,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 2 Services', 'description': 'Book certified mental wellness & counselling service variation 2 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 2', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '8779e21f-7909-588c-8d1f-c83a1d0ce9f6',
        "name": 'Mental Wellness & Counselling Service Variation 3',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 1250,
        "duration_minutes": 90,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 3 Services', 'description': 'Book certified mental wellness & counselling service variation 3 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 3', 'health', 'fitness', 'wellness']},
    },
    {
        "id": 'e802b517-8b47-5d0b-b47a-6768c187a156',
        "name": 'Mental Wellness & Counselling Service Variation 4',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 1400,
        "duration_minutes": 105,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 4 Services', 'description': 'Book certified mental wellness & counselling service variation 4 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 4', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '5b7013df-172b-5a09-ab5e-6363466c7fb6',
        "name": 'Mental Wellness & Counselling Service Variation 5',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 1550,
        "duration_minutes": 120,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 5 Services', 'description': 'Book certified mental wellness & counselling service variation 5 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 5', 'health', 'fitness', 'wellness']},
    },
    {
        "id": '2ba5e27c-d7ff-5126-ab96-d424a12c30d2',
        "name": 'Mental Wellness & Counselling Service Variation 6',
        "category": '9. Health, Fitness & Wellness',
        "subcategory": 'Mental Wellness & Counselling',
        "price": 1700,
        "duration_minutes": 135,
        "description": 'Professional mental wellness & counselling service designed for holistic well-being.',
        "highlights": ['Certified Mental Wellness & Counselling specialist', 'Personalised programme', 'Home or studio visits available', 'Progress tracking included'],
        "included": ['Initial health assessment', 'Customised session plan', 'Post-session feedback', 'Digital progress report'],
        "excluded": ['Gym membership or equipment costs', 'Prescription medications'],
        "process_steps": [{'step_number': 1, 'title': 'Initial Consultation', 'description': 'Assessing health goals, medical history, and current fitness level'}, {'step_number': 2, 'title': 'Plan Design', 'description': 'Creating a customised programme tailored to specific needs'}, {'step_number': 3, 'title': 'Session Execution', 'description': 'Conducting guided sessions with professional supervision'}, {'step_number': 4, 'title': 'Progress Monitoring', 'description': 'Tracking improvements and adjusting the programme'}, {'step_number': 5, 'title': 'Follow-Up & Review', 'description': 'Reviewing outcomes and setting next phase goals'}],
        "tools_materials": ['Assessment forms', 'Exercise equipment (as required)', 'Nutritional guides', 'Digital tracking tools'],
        "customer_setup": ['Wear comfortable clothing', 'Ensure adequate space for sessions', 'Keep hydrated'],
        "aftercare": ['Follow post-session cool-down routines', 'Adhere to recommended diet and rest'],
        "expected_results": 'Improved fitness levels, reduced pain, and enhanced mental well-being.',
        "important_notes": 'Please disclose any medical conditions before sessions begin.',
        "warranty": 'Free rescheduling for trainer cancellations; first-session satisfaction guarantee.',
        "faqs": [{'question': 'Do I need prior experience?', 'answer': 'No prior experience is needed; programmes are tailored to all fitness levels.'}, {'question': 'Can sessions happen at my home?', 'answer': 'Yes, we offer in-home, studio, and online sessions.'}, {'question': 'How soon will I see results?', 'answer': 'Most clients notice improvements within 4-6 weeks with consistent sessions.'}, {'question': 'Are the professionals certified?', 'answer': 'Yes, all our health professionals hold valid certifications from recognised bodies.'}],
        "tips": ['Stay consistent — even 3 sessions per week makes a significant difference.'],
        "dos": ['Communicate openly about pain or discomfort during sessions.'],
        "donts": ['Do not skip prescribed rest days.'],
        "service_features": ['Certified Professionals', 'Guaranteed Quality', 'Flexible Scheduling'],
        "service_media": [],
        "seo_metadata": {'title': 'Professional Mental Wellness & Counselling Service Variation 6 Services', 'description': 'Book certified mental wellness & counselling service variation 6 for your health and wellness needs.', 'keywords': ['mental wellness & counselling service variation 6', 'health', 'fitness', 'wellness']},
    },
]
